from . import help
from . import start
from . import menuDasturlash
from . import cppMenu
from . import pythonMenu
from . import kotlinMenu
from . import menuMobilograf
from . import menuKopiryating
from . import echo